### ISSUE TITLE
NextJS pages router: Module not found turbopack-ecmascript-runtime

### ISSUE THREAD

**Issue by fgeierst** [premieroctet/next-admin#159] opened 2024-02-29 08:02 UTC
I followed the [installation guide](https://next-admin.js.org/docs/getting-started#installation) for the Next JS pages router setup, but see this error:

> ./node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/internal/helpers/use-websocket.js:86:8
Module not found: Can't resolve '@vercel/turbopack-ecmascript-runtime/dev/client/hmr-client.ts'
Import trace for requested module: 
(...)
./src/pages/admin/[[...nextadmin]].tsx  

Here is a reduced test case: https://github.com/fgeierst/t3-next-admin-pages-router

**Comment by Siglave** [comment] 2024-03-05 19:35
I have the same issue

**Comment by foyarash** [comment] 2024-03-11 09:54
Hello,

The error has been fixed in version 3.2.7. Please update the library.

However i reproduced a serialization error with your options, I will have a look into it and deploy a fix for this ASAP

**Comment by foyarash** [comment] 2024-03-11 14:57
Serialization error was actually because of a missing superjson plugin, documentation has been updated accordingly.

**Closed by foyarash** 2024-03-11 14:57 UTC

**Comment by fgeierst** [comment] 2024-03-11 15:06
Thanks! This works for me, too. I updated the [demo repository](https://github.com/fgeierst/t3-next-admin-pages-router).
