### ISSUE TITLE
[BUG] - Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by zbeyens** [premieroctet/next-admin#275] opened 2024-05-14 09:33 UTC
### Description

For such schema:

```prisma
model Vote {
  id      String  @id @default(cuid())
  userId  String
  User    User    @relation(fields: [userId], references: [id], onDelete: Cascade)
  showId  String?
  Show    Show?   @relation(fields: [showId], references: [id], onDelete: Cascade)
  mediaId String?
  Media   Media?  @relation(fields: [mediaId], references: [id], onDelete: Cascade)

  value Int @default(1)

  @@unique([userId, showId])
  @@unique([userId, mediaId])
}

// happens as well for:
model ShowGenre {
  id      String @id @default(cuid())
  showId  String
  Show    Show   @relation(fields: [showId], references: [id], onDelete: Cascade)
  genreId String
  Genre   Genre  @relation(fields: [genreId], references: [id], onDelete: Cascade)

  @@unique([showId, genreId])
}
```

### Reproduction steps

- Go to `/vote` page

### Next router

App router

### Next Admin version

4.2.0

### Next Admin options

Default

### Logs

```bash
Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at $RS (vote:1:32755)
    at vote:312:59529
```

### Browsers

Chrome

**Comment by cregourd** [comment] 2024-05-15 09:32
Hi, are you using some Rich Text Editor in your options ? We think  that come from there, but we need more precision on your options config

**Comment by zbeyens** [comment] 2024-05-15 10:16
I'm currently using

```
export const adminOptions: NextAdminOptions = {
  basePath: '/studio/admin',
  model: { Vote: {} }
}
```

**Comment by foyarash** [comment] 2024-09-04 12:23
Closing since we are not able to reproduce

**Closed by foyarash** 2024-09-04 12:23 UTC
Labels: bug
