### ISSUE TITLE
[FEATURE] - Set default value from session or with a function call

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#274] opened 2024-05-13 23:10 UTC
### Summary

I'd like to be able to grab a user from the session and set that user as the author of a new record.

### Basic Example

Admin joe@user.com logins to the admin view. Joe creates a new record. By default his user is set as the author of the new record on the author field.

### Unresolved questions

people implement auth in different ways, and use different fields to express this, and there could be other uses for this kind of functionality, so I imagine one solution is to set a default value dynamically based on some kind of function call.

**Comment by foyarash** [comment] 2024-05-14 08:42
This looks like a duplicate of https://github.com/premieroctet/next-admin/issues/197

Basically you should be able to do this by adding your own logic before calling the submitForm server action

**Closed** 2024-05-14 14:51 UTC
Labels: enhancement
